// Generated by CoffeeScript 1.8.0
var sync_object;

sync_object = {
  "GDrive": {
    "key": "424243246254-n6b2v8j4j09723ktif41ln247n75pnts.apps.googleusercontent.com",
    "scope": "openid https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/plus.me",
    "app_name": "taskstrike",
    "app_id": '424243246254'
  },
  "Dropbox": {
    "key": "q5yx30gr8mcvq4f",
    "secret": "qy64qphr70lwui5",
    "app_name": "taskstrike"
  }
};

Nimbus.Auth.setup(sync_object);
